#设置端口
server:
  port: 9191
spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://59.110.158.131:3306/msp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: msp
    password: nCWABcJYidYYJYrE
    driver-class-name: com.mysql.jdbc.Driver
  #邮箱配置
  mail:
    #配置smtp服务主机地址
    # qq邮箱为smtp.qq.com          端口号465或587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       端口号465或994
    # 126     smtp.126.com
    host: smtp.126.com
    #发送者邮箱
    username: BCM666@126.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: ZQUHYTEJFFESSKPW
    #端口号465 25或587端口是非ssl
    port: 25
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            useEhlo: true
            useAuth: false
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  #Redis配置
  redis:
    host: 59.110.158.131
    port: 6379
    password: mspredispassword
  rabbitmq:
    host: 59.110.158.131
    port: 5672
    virtual-host: MSP
    username: vortex
    password: 123456
  main:
    log-startup-info: false
#配置mybatis
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#配置日志框架
logging:
  config: classpath:config/logback-spring.xml
  level:
    org.springframework: info
    org.hibernate: info
    com.zaxxer: info
    org.mybatis: info
